services:
 scheduler:
  image: deproject-dibimbing/airflow
  container_name: ${AIRFLOW_SCHEDULER_CONTAINER_NAME}
  hostname: ${AIRFLOW_SCHEDULER_CONTAINER_NAME}
  command: scheduler
  restart: always
  environment:
   - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_CONTAINER_NAME}/${POSTGRES_DB}
   - AIRFLOW__CORE__EXECUTOR=LocalExecutor
   - POSTGRES_USER=${POSTGRES_USER}
   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
   - POSTGRES_DB=${POSTGRES_DB}
   - POSTGRES_DW_DB=${POSTGRES_DW_DB}
   - POSTGRES_CONTAINER_NAME=${POSTGRES_CONTAINER_NAME}
   - POSTGRES_PORT=${POSTGRES_PORT}
   - SPARK_MASTER_HOST_NAME=${SPARK_MASTER_HOST_NAME}
   - SPARK_MASTER_PORT=${SPARK_MASTER_PORT}
  volumes:
   - ../dags:/opt/airflow/dags
   - ../logs:/opt/airflow/logs
   - ../data:/opt/bitnami/spark/data
   - ../data:/opt/airflow/data
   - ../cred:/opt/airflow/cred
   - ../spark-scripts:/spark-scripts
   - ../scripts:/scripts
   - ../spark-jars:/opt/bitnami/spark/jars

 webserver:
  image: deproject-dibimbing/airflow
  container_name: ${AIRFLOW_WEBSERVER_CONTAINER_NAME}
  hostname: ${AIRFLOW_WEBSERVER_CONTAINER_NAME}
  entrypoint: /scripts/entrypoint.sh
  restart: always
  depends_on:
   - scheduler
  environment:
   - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_CONTAINER_NAME}/${POSTGRES_DB}
   - AIRFLOW__CORE__EXECUTOR=LocalExecutor
   - POSTGRES_USER=${POSTGRES_USER}
   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
   - POSTGRES_DB=${POSTGRES_DB}
   - POSTGRES_DW_DB=${POSTGRES_DW_DB}
   - POSTGRES_CONTAINER_NAME=${POSTGRES_CONTAINER_NAME}
   - POSTGRES_PORT=${POSTGRES_PORT}
   - SPARK_MASTER_HOST_NAME=${SPARK_MASTER_HOST_NAME}
   - SPARK_MASTER_PORT=${SPARK_MASTER_PORT}
  volumes:
   - ../dags:/opt/airflow/dags
   - ../logs:/opt/airflow/logs
   - ../data:/opt/bitnami/spark/data
   - ../data:/opt/airflow/data
   - ../cred:/opt/airflow/cred
   - ../spark-scripts:/spark-scripts
   - ../scripts:/scripts
   - ../spark-jars:/opt/bitnami/spark/jars
  ports:
   - ${AIRFLOW_WEBSERVER_PORT}:8080

networks:
 default:
  name: deproject-network
  external: true
